version: '3.8'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: movie-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./server
    container_name: movie-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - SPRING_APPLICATION_NAME=Movie
      - SPRING_DATA_MONGODB_DATABASE=movie-api
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/movie-api
    ports:
      - "8080:8080"

  frontend:
    build: ./client
    container_name: movie-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
